### ISSUE TITLE
xbArticleMan: Es ist ein Fehler aufgetreten.      1146 Table 'n7ack1gj_hveev_db.j5_categories' doesn't exist 

### ISSUE THREAD

**Issue by BernSgo** [rogercreagh/j5-xbArticleMan#3]
**Describe the bug**
Starting Dashboard shows: 1146 Table 'n7ack1gj_hveev_db.j5_categories' doesn't exist 

**To Reproduce**
All other items work fine, only dashboard of xbArticleMan show this error

**Expected behavior**
How to solve this gatabase problem

**Screenshots**
![xbArticleMan_Montag, 10  Juni 2024_08h57m07s_001_](https://github.com/rogercreagh/j5-xbArticleMan/assets/165266578/78d8830f-4d47-4bb3-b856-87f58120bf7d)

**Server (please provide at least Joomla and php versions)
 - Joomla Version: [5.1.1]
 - PHP Version [8.2.16]
 - MySQL version 8.0.26-16
 - Server type and OS [Linux Provider version]

**Client (please complete the following information):**
 - Type [Windows PC]
 - Device OS Version Windows 10 newest
 - Browser [firefox and othersi]

**Additional context**
Any idea how to solve my problem?

Warm regards Bernhard

**Comment by rogercreagh** [comment]
Whoops! Thanks @BernSgo 

As you can guess at present all my J5 sites (only a few so far,most still J3 pending update of my components ) use `j5_` as the table prefix (because I don't like the random prefix and want to be able to simply see which are J5 and which are J3 when looking in mysql on a server) hence this hasn't shown up in my testing and has been there since v5.0.0.0. My mistake!

Now fixed - you should be able to simply update from within Joomla Extensions Management on your site and it'll come good.
Very sorry about that.

**Comment by rogercreagh** [comment]
Fixed in version 5.0.0.2 and zip file available in releases folder on here (I really must work out how to use the github releases system someday) and on [crosborne.uk](https://crosborne.uk/component/phocadownload/file/27-xbarticleman-j5) and linked from JED
